name: "Approve Hotfix Action"
description: "A GitHub action for approving hotfix pull requests."
branding:
  icon: "check-circle"
  color: "white"
inputs:
  repo-token:
    description: "Repo auth token."
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
